package main 

type VietChar struct {
	Target 		rune
	Modifier	rune
}

var (
	telexMod = map[VietChar]string{
		// lowercase
		{Target: 'a', Modifier: 'a'}: "â",
		{Target: 'e', Modifier: 'e'}: "ê",
		{Target: 'o', Modifier: 'o'}: "ô",

		{Target: 'a', Modifier: 'w'}: "ă",
		{Target: 'o', Modifier: 'w'}: "ơ",
		{Target: 'u', Modifier: 'w'}: "ư",

		{Target: 'a', Modifier: 's'}: "á",
		{Target: 'e', Modifier: 's'}: "é",
		{Target: 'i', Modifier: 's'}: "í",
		{Target: 'o', Modifier: 's'}: "ó",
		{Target: 'u', Modifier: 's'}: "ú",
		{Target: 'ă', Modifier: 's'}: "ắ",
		{Target: 'â', Modifier: 's'}: "ấ",
		{Target: 'ê', Modifier: 's'}: "ế",
		{Target: 'ô', Modifier: 's'}: "ố",
		{Target: 'ơ', Modifier: 's'}: "ớ",
		{Target: 'ư', Modifier: 's'}: "ứ",

		{Target: 'a', Modifier: 'f'}: "à",
		{Target: 'e', Modifier: 'f'}: "è",
		{Target: 'i', Modifier: 'f'}: "ì",
		{Target: 'o', Modifier: 'f'}: "ò",
		{Target: 'u', Modifier: 'f'}: "ù",
		{Target: 'ă', Modifier: 'f'}: "ằ",
		{Target: 'â', Modifier: 'f'}: "ầ",
		{Target: 'ê', Modifier: 'f'}: "ề",
		{Target: 'ô', Modifier: 'f'}: "ồ",
		{Target: 'ơ', Modifier: 'f'}: "ờ",
		{Target: 'ư', Modifier: 'f'}: "ừ",

		{Target: 'a', Modifier: 'r'}: "ả",
		{Target: 'e', Modifier: 'r'}: "ẻ",
		{Target: 'i', Modifier: 'r'}: "ỉ",
		{Target: 'o', Modifier: 'r'}: "ỏ",
		{Target: 'u', Modifier: 'r'}: "ủ",
		{Target: 'ă', Modifier: 'r'}: "ẳ",
		{Target: 'â', Modifier: 'r'}: "ẩ",
		{Target: 'ê', Modifier: 'r'}: "ể",
		{Target: 'ô', Modifier: 'r'}: "ổ",
		{Target: 'ơ', Modifier: 'r'}: "ở",
		{Target: 'ư', Modifier: 'r'}: "ử",

		{Target: 'a', Modifier: 'x'}: "ã",
		{Target: 'e', Modifier: 'x'}: "ẽ",
		{Target: 'i', Modifier: 'x'}: "ĩ",
		{Target: 'o', Modifier: 'x'}: "õ",
		{Target: 'u', Modifier: 'x'}: "ũ",
		{Target: 'ă', Modifier: 'x'}: "ẵ",
		{Target: 'â', Modifier: 'x'}: "ẫ",
		{Target: 'ê', Modifier: 'x'}: "ễ",
		{Target: 'ô', Modifier: 'x'}: "ỗ",
		{Target: 'ơ', Modifier: 'x'}: "ỡ",
		{Target: 'ư', Modifier: 'x'}: "ữ",

		{Target: 'a', Modifier: 'j'}: "ạ",
		{Target: 'e', Modifier: 'j'}: "ẹ",
		{Target: 'i', Modifier: 'j'}: "ị",
		{Target: 'o', Modifier: 'j'}: "ọ",
		{Target: 'u', Modifier: 'j'}: "ụ",
		{Target: 'ă', Modifier: 'j'}: "ặ",
		{Target: 'â', Modifier: 'j'}: "ậ",
		{Target: 'ê', Modifier: 'j'}: "ệ",
		{Target: 'ô', Modifier: 'j'}: "ộ",
		{Target: 'ơ', Modifier: 'j'}: "ợ",
		{Target: 'ư', Modifier: 'j'}: "ự",

		{Target: 'd', Modifier: 'd'}: "đ",

		// uppercase 
		{Target: 'A', Modifier: 'A'}: "Â",
        {Target: 'E', Modifier: 'E'}: "Ê",
        {Target: 'O', Modifier: 'O'}: "Ô",

        {Target: 'A', Modifier: 'W'}: "Ă",
        {Target: 'O', Modifier: 'W'}: "Ơ",
        {Target: 'U', Modifier: 'W'}: "Ư",

        {Target: 'A', Modifier: 'S'}: "Á",
        {Target: 'E', Modifier: 'S'}: "É",
        {Target: 'I', Modifier: 'S'}: "Í",
        {Target: 'O', Modifier: 'S'}: "Ó",
        {Target: 'U', Modifier: 'S'}: "Ú",
        {Target: 'Ă', Modifier: 'S'}: "Ắ",
        {Target: 'Â', Modifier: 'S'}: "Ấ",
        {Target: 'Ê', Modifier: 'S'}: "Ế",
        {Target: 'Ô', Modifier: 'S'}: "Ố",
        {Target: 'Ơ', Modifier: 'S'}: "Ớ",
        {Target: 'Ư', Modifier: 'S'}: "Ứ",

        {Target: 'A', Modifier: 'F'}: "À",
        {Target: 'E', Modifier: 'F'}: "È",
        {Target: 'I', Modifier: 'F'}: "Ì",
        {Target: 'O', Modifier: 'F'}: "Ò",
        {Target: 'U', Modifier: 'F'}: "Ù",
        {Target: 'Ă', Modifier: 'F'}: "Ằ",
        {Target: 'Â', Modifier: 'F'}: "Ầ",
        {Target: 'Ê', Modifier: 'F'}: "Ề",
        {Target: 'Ô', Modifier: 'F'}: "Ồ",
        {Target: 'Ơ', Modifier: 'F'}: "Ờ",
        {Target: 'Ư', Modifier: 'F'}: "Ừ",

        {Target: 'A', Modifier: 'R'}: "Ả",
        {Target: 'E', Modifier: 'R'}: "Ẻ",
        {Target: 'I', Modifier: 'R'}: "Ỉ",
        {Target: 'O', Modifier: 'R'}: "Ỏ",
        {Target: 'U', Modifier: 'R'}: "Ủ",
        {Target: 'Ă', Modifier: 'R'}: "Ẳ",
        {Target: 'Â', Modifier: 'R'}: "Ẩ",
        {Target: 'Ê', Modifier: 'R'}: "Ể",
        {Target: 'Ô', Modifier: 'R'}: "Ổ",
        {Target: 'Ơ', Modifier: 'R'}: "Ở",
        {Target: 'Ư', Modifier: 'R'}: "Ử",

        {Target: 'A', Modifier: 'X'}: "Ã",
        {Target: 'E', Modifier: 'X'}: "Ẽ",
        {Target: 'I', Modifier: 'X'}: "Ĩ",
        {Target: 'O', Modifier: 'X'}: "Õ",
        {Target: 'U', Modifier: 'X'}: "Ũ",
        {Target: 'Ă', Modifier: 'X'}: "Ẵ",
        {Target: 'Â', Modifier: 'X'}: "Ẫ",
        {Target: 'Ê', Modifier: 'X'}: "Ễ",
        {Target: 'Ô', Modifier: 'X'}: "Ỗ",
        {Target: 'Ơ', Modifier: 'X'}: "Ỡ",
        {Target: 'Ư', Modifier: 'X'}: "Ữ",

        {Target: 'A', Modifier: 'J'}: "Ạ",
        {Target: 'E', Modifier: 'J'}: "Ẹ",
        {Target: 'I', Modifier: 'J'}: "Ị",
        {Target: 'O', Modifier: 'J'}: "Ọ",
        {Target: 'U', Modifier: 'J'}: "Ụ",
        {Target: 'Ă', Modifier: 'J'}: "Ặ",
        {Target: 'Â', Modifier: 'J'}: "Ậ",
        {Target: 'Ê', Modifier: 'J'}: "Ệ",
        {Target: 'Ô', Modifier: 'J'}: "Ộ",
        {Target: 'Ơ', Modifier: 'J'}: "Ợ",
        {Target: 'Ư', Modifier: 'J'}: "Ự",

        {Target: 'D', Modifier: 'D'}: "Đ",
	}

	passThroughKeys = map[string]bool{
		"BackSpace": true,
		"Escape": true,
		"Tab": true,
		"Print": true,
		"Scroll_Lock": true,
		"Pause": true,
		"Insert": true,
		"Delete": true,
		"Home": true,
		"End": true,
		"Prior": true,        
		"Next": true,         
		"Up": true,
		"Down": true,
		"Left": true,
		"Right": true,
		"Menu": true,         
		"Caps_Lock": true,
		"Num_Lock": true,
		"Super_L": true,     
		"Super_R": true,
		"Alt_L": true,
		"Alt_R": true,
		"Control_L": true,
		"Control_R": true,
		"Shift_L": true,
		"Shift_R": true,
	}

)